name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate on Docker Hub
        run: echo "Running Docker Login"
      - name: Build Docker Image
        run: echo "Running Docker build"
      - name: Docker Push
        run: "Running Docker push"
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate on AWS
        run: echo "Running aws configure"
      - name: Setup kubectl
        run: echo "Running aws eks update-kubeconfig
      - name: Deploy Kubernetes
        run: "Running kubectl apply"
    
